# Generated by Django 4.0.5 on 2022-07-16 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MATRIC_NO', models.CharField(blank=True, max_length=10)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='profile_pic')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
